[package]
name = "galaxy"
version = "0.1.0"
authors = ["Dmitry Polyanitsa <coffeecup.winner@gmail.com>"]
edition = "2018"

[dependencies]
bmp = "^0.5"
fltk = "^0.7"
http-body = "0.3.1"
hyper = "0.13.7"
hyper-tls = "0.4.3"
tokio = { version = "0.2.22", features = ["macros"] }
